### ISSUE TITLE
Triline menu doesn't open on mobile safari

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape-home#16]
Try opening the three-line menu icon on safari. Doesn't work
It doesn't work on Chrome or Firefox either.

Browser's console error:

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: <a />. Did you accidentally export a JSX literal instead of a component?
    at Ke3 (http://localhost:5173/node_modules/.vite/deps/@headlessui_react.js?v=171efaf3:3097:13)
    at MobileNavLink
    at div
    at div
    at MotionComponent (http://localhost:5173/node_modules/.vite/deps/framer-motion.js?v=171efaf3:430:40)
    at Ye4 (http://localhost:5173/node_modules/.vite/deps/@headlessui_react.js?v=171efaf3:3168:13)
    at PresenceChild (http://localhost:5173/node_modules/.vite/deps/framer-motion.js?v=171efaf3:7139:24)
    at AnimatePresence (http://localhost:5173/node_modules/.vite/deps/framer-motion.js?v=171efaf3:7205:26)
    at div
    at http://localhost:5173/node_modules/.vite/deps/@headlessui_react.js?v=171efaf3:2002:70
    at s9 (http://localhost:5173/node_modules/.vite/deps/@headlessui_react.js?v=171efaf3:1256:22)
    at Ue2 (http://localhost:5173/node_modules/.vite/deps/@headlessui_react.js?v=171efaf3:3066:21)
    at div
    at div
    at Container (http://localhost:5173/src/components/Container.jsx:18:29)
    at nav
    at header
    at Header
    at Layout (http://localhost:5173/src/components/Layout.jsx:19:26)
```

**Comment by chrtannus** [comment]
@maxkfranz Can you please try again? It should be fixed now.
